### ISSUE TITLE
这是谷粒随享项目吗？

### ISSUE THREAD

**Issue by js-yabei** [prince-g/GitHtubGuliShare#1]
能否分享一下项目资源？谢谢

**Comment by prince-g** [comment]
可以给你课件。

**Comment by js-yabei** [comment]
> 可以给你课件。

谢谢

**Comment by prince-g** [comment]
所以，我应该怎么给你。

**Comment by js-yabei** [comment]
> 所以，我应该怎么给你。

能给个百度网盘链接吗？

**Comment by prince-g** [comment]
链接：https://pan.baidu.com/s/12adaEY5o36dJT28UTbyQJg?pwd=3k2a 
提取码：3k2a

**Comment by js-yabei** [comment]
> 链接：https://pan.baidu.com/s/12adaEY5o36dJT28UTbyQJg?pwd=3k2a 
> 提取码：3k2a

谢谢

**Comment by Ustinian1722** [comment]
能否给一下课件？1722883727@qq.com

**Comment by hongshl** [comment]
> 链接：https://pan.baidu.com/s/12adaEY5o36dJT28UTbyQJg?pwd=3k2a 提取码：3k2a

你好，链接失效了，能重新发一下吗？

**Comment by js-yabei** [comment]
> 能否给一下课件？[1722883727@qq.com](mailto:1722883727@qq.com)

链接：https://pan.baidu.com/s/1OE1i2VFBBIGKY1DxAtF6KA 
提取码：lu0s 
--来自百度网盘超级会员V8的分享

**Comment by js-yabei** [comment]
> > 链接：https://pan.baidu.com/s/12adaEY5o36dJT28UTbyQJg?pwd=3k2a 提取码：3k2a
> 
> 你好，链接失效了，能重新发一下吗？

链接：https://pan.baidu.com/s/1OE1i2VFBBIGKY1DxAtF6KA 
提取码：lu0s 
--来自百度网盘超级会员V8的分享

**Comment by prince-g** [comment]
> > 链接：https://pan.baidu.com/s/12adaEY5o36dJT28UTbyQJg?pwd=3k2a 提取码：3k2a
> 
> 你好，链接失效了，能重新发一下吗？

看来不需要我了，这里有视频，课件我找不到了。【快传】我给你发了 谷粒随享, 快来看看 https://www.alipan.com/t/ret4h2SEoxqu4MmwlAul 点击链接即可保存。「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。

**Comment by hongshl** [comment]
> > > 链接：https://pan.baidu.com/s/12adaEY5o36dJT28UTbyQJg?pwd=3k2a 提取码：3k2a
> > 
> > 
> > 你好，链接失效了，能重新发一下吗？
> 
> 看来不需要我了，这里有视频，课件我找不到了。【快传】我给你发了 谷粒随享, 快来看看 https://www.alipan.com/t/ret4h2SEoxqu4MmwlAul 点击链接即可保存。「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。

谢谢

**Comment by hongshl** [comment]
> > > 链接：https://pan.baidu.com/s/12adaEY5o36dJT28UTbyQJg?pwd=3k2a 提取码：3k2a
> > 
> > 
> > 你好，链接失效了，能重新发一下吗？
> 
> 链接：https://pan.baidu.com/s/1OE1i2VFBBIGKY1DxAtF6KA 提取码：lu0s --来自百度网盘超级会员V8的分享

谢谢

**Comment by js-yabei** [comment]
> > > 链接：https://pan.baidu.com/s/12adaEY5o36dJT28UTbyQJg?pwd=3k2a 提取码：3k2a
> > 
> > 
> > 你好，链接失效了，能重新发一下吗？
> 
> 看来不需要我了，这里有视频，课件我找不到了。【快传】我给你发了 谷粒随享, 快来看看 https://www.alipan.com/t/ret4h2SEoxqu4MmwlAul 点击链接即可保存。「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。

视频我还没保存呢，怎么这么快就失效了，能重发一遍吗？

**Comment by prince-g** [comment]
> > > > 链接：https://pan.baidu.com/s/12adaEY5o36dJT28UTbyQJg?pwd=3k2a 提取码：3k2a
> > > 
> > > 
> > > 你好，链接失效了，能重新发一下吗？
> > 
> > 看来不需要我了，这里有视频，课件我找不到了。【快传】我给你发了 谷粒随享, 快来看看 https://www.alipan.com/t/ret4h2SEoxqu4MmwlAul 点击链接即可保存。「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。
> 
> 视频我还没保存呢，怎么这么快就失效了，能重发一遍吗？

【快传】我给你发了 谷粒随享, 快来看看 https://www.alipan.com/t/dQO3Xqus767kFmoDxIKa 点击链接即可保存。「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。

**Comment by js-yabei** [comment]
> > > > > 链接：https://pan.baidu.com/s/12adaEY5o36dJT28UTbyQJg?pwd=3k2a 提取码：3k2a
> > > > 
> > > > 
> > > > 你好，链接失效了，能重新发一下吗？
> > > 
> > > 
> > > 看来不需要我了，这里有视频，课件我找不到了。【快传】我给你发了 谷粒随享, 快来看看 https://www.alipan.com/t/ret4h2SEoxqu4MmwlAul 点击链接即可保存。「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。
> > 
> > 
> > 视频我还没保存呢，怎么这么快就失效了，能重发一遍吗？
> 
> 【快传】我给你发了 谷粒随享, 快来看看 https://www.alipan.com/t/dQO3Xqus767kFmoDxIKa 点击链接即可保存。「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。

保存上了，谢谢！
